default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: irina_api_dev

test:
  <<: *default
  database: irina_api_test

production:
  <<: *default
  database: irina_api_prod
  username: myapp
  password: <%= ENV['IRINA_API_DATABASE_PASSWORD'] %>
